field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  a9b04057-43c7-498d-8c38-46f648dac87e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3f91a3c8-c8cd-4c77-a00f-f9cfa4e72ca0 # Articles Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7adc5ea4-ba9a-49ac-be2a-a5217f2c66b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a2f86a1-01ab-41dd-a9ba-aafc90a39cda # Articles Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13072979-86ee-44ef-8865-c91d50d2502a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0470c53b-4db1-4ec1-afaa-bb242a41a42a
        userCondition: null
fields:
  1a2f86a1-01ab-41dd-a9ba-aafc90a39cda: # Articles Panel Heading
    columnSuffix: ezakepgj
    contentColumnType: text
    fieldGroup: null
    handle: articlesPanelHeading
    instructions: null
    name: 'Articles Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3f91a3c8-c8cd-4c77-a00f-f9cfa4e72ca0: # Articles Limit
    columnSuffix: ozuibgcm
    contentColumnType: smallint(1)
    fieldGroup: null
    handle: articlesLimit
    instructions: null
    name: 'Articles Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 6
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: articlesRollup
name: 'Articles Rollup'
sortOrder: 9
