field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  41f5f316-0002-44ab-9467-8949489059b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dd527bbc-9bc5-4fd3-96cc-99f1f11478cb # Articles Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc2f77ec-475a-4512-a0e2-b656f6c5c223
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c2cba99-73ff-4f1f-8382-7c60d6f8b921 # Articles Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a123c91-f83c-43e7-9894-e1595389d40d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b6519b28-777b-45da-a480-6793046611c6
        userCondition: null
fields:
  9c2cba99-73ff-4f1f-8382-7c60d6f8b921: # Articles Panel Heading
    columnSuffix: jbjcaghl
    contentColumnType: text
    fieldGroup: null
    handle: articlesPanelHeading
    instructions: null
    name: 'Articles Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd527bbc-9bc5-4fd3-96cc-99f1f11478cb: # Articles Limit
    columnSuffix: kfngxcou
    contentColumnType: smallint(1)
    fieldGroup: null
    handle: articlesLimit
    instructions: null
    name: 'Articles Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 6
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: articlesRollup
name: 'Articles Rollup'
sortOrder: 8
