field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  866a41f1-82df-4680-b5d7-681f503fe7dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c5adc8c-5eec-42ca-a6e3-016f94507311
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16e454de-1fea-4084-a4c2-b02a1e2d5276
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebe6ba6b-899c-45dd-bd63-b5a548930597
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dfb8cd7-197d-4e77-b6c3-cc9eaccfeb14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: efa945fb-f7e9-4e78-969d-4ba4994e05d0
        userCondition: null
fields:
  8c5adc8c-5eec-42ca-a6e3-016f94507311:
    columnSuffix: zregwrma
    contentColumnType: smallint(1)
    fieldGroup: null
    handle: articlesLimit
    instructions: null
    name: 'Articles Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 6
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ebe6ba6b-899c-45dd-bd63-b5a548930597:
    columnSuffix: nowwmsiu
    contentColumnType: text
    fieldGroup: null
    handle: articlesPanelHeading
    instructions: null
    name: 'Articles Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: articlesRollup
name: 'Articles Rollup'
sortOrder: 7
