field: 8d7b11e3-8a9f-4551-8e59-559d5a419a6d # Content Home
fieldLayouts:
  86bc83ab-ba6b-4139-a131-ded96be54d20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 82e76961-db81-4d96-883f-d175d4b37a02 # Articles Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 712bb6c5-b97d-4450-87d9-309a09c5ce2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b175d539-5ad7-42c4-a0e1-84d91fa7fbeb # Articles Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee46e8ed-7846-44be-bb28-0a4c8a6ed1fc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ddec79d-6ec4-44c2-9682-e0465a3d2a2f
        userCondition: null
fields:
  82e76961-db81-4d96-883f-d175d4b37a02: # Articles Limit
    columnSuffix: ptfwikbg
    contentColumnType: smallint(1)
    fieldGroup: null
    handle: articlesLimit
    instructions: null
    name: 'Articles Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: 6
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  b175d539-5ad7-42c4-a0e1-84d91fa7fbeb: # Articles Panel Heading
    columnSuffix: nmzokjol
    contentColumnType: text
    fieldGroup: null
    handle: articlesPanelHeading
    instructions: null
    name: 'Articles Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: articlesRollup
name: 'Articles Rollup'
sortOrder: 2
