field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  439a9243-6292-44ae-9f31-dd51225a4882:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 932dee3c-286f-4861-b6ff-beac523b1af2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de0176fd-e541-437e-a484-984bf7f8ab3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51a35042-bbb4-402e-b4fe-74e6059ddd19
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63df1854-594e-428f-9d37-553e38dbbe2b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2049cdf8-97b7-4493-9362-34162d74bbcc
        userCondition: null
fields:
  51a35042-bbb4-402e-b4fe-74e6059ddd19:
    columnSuffix: soahywbf
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  932dee3c-286f-4861-b6ff-beac523b1af2:
    columnSuffix: agaxteua
    contentColumnType: text
    fieldGroup: null
    handle: author
    instructions: null
    name: Author
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockQuote
name: Quote
sortOrder: 6
