field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  d2b38440-d009-4246-8a48-f202593f183e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 18d9b59f-c657-43cc-9f56-86e39d26f05d # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74a00bf8-1066-4bf7-b0e8-9443a758150a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3bdb14bb-198f-4215-b8de-a6e127793112 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c41ae770-9132-484e-af85-01291e7e4541
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25904031-218a-4e64-8f90-f7a1f52e0735
        userCondition: null
fields:
  3bdb14bb-198f-4215-b8de-a6e127793112: # Quote
    columnSuffix: ahvssrgs
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  18d9b59f-c657-43cc-9f56-86e39d26f05d: # Author
    columnSuffix: kczxsjfe
    contentColumnType: text
    fieldGroup: null
    handle: author
    instructions: null
    name: Author
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockQuote
name: Quote
sortOrder: 7
