field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  b4c2d9df-d6ee-4316-828e-f2332a4c976b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f54c914-b290-4262-a899-9015af4f4d50 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99b84e45-2cdd-46cb-802d-7f3ccddf2af8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 570a2853-0b4d-4b86-b142-0d7ad3c1a37f # Items
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00dcd52a-6076-4e5a-8172-209e2e20d120
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5770d180-bbfb-4d10-8136-d82b490d10cd
        userCondition: null
fields:
  2f54c914-b290-4262-a899-9015af4f4d50: # Heading
    columnSuffix: dpxpyowo
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  570a2853-0b4d-4b86-b142-0d7ad3c1a37f: # Items
    columnSuffix: sroqdrdv
    contentColumnType: text
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - item
                -
                  - handle
                  - item
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: bullets
name: Bullets
sortOrder: 7
