field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  a24aecfd-f957-40b3-aa3c-f13a5231a3ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 750a6a46-5608-44ac-963d-8472c1d3cd40 # Title (h2)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37dcea11-5717-4443-917f-177325a04603
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33356ed5-ee39-4b15-8762-22970231ddf4 # Sub Heading (h3)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4d4c5de-5566-486c-a1c1-aac3417c6671
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 145aee74-93e9-46ed-9aff-61c7d2294c45 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a46c6f4d-22ac-4f4f-9802-0a1d6de60332
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 753acc38-d212-4067-8c54-326b6007ffac # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2075291-e1fc-42a9-87d6-16c88202aa81
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c29dc667-31ef-405a-aeee-bc2a055b8010
        userCondition: null
fields:
  145aee74-93e9-46ed-9aff-61c7d2294c45: # Content
    columnSuffix: jygcjbtq
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms:
        - 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  750a6a46-5608-44ac-963d-8472c1d3cd40: # Title (h2)
    columnSuffix: vtptjspb
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: 'Title (h2)'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  753acc38-d212-4067-8c54-326b6007ffac: # Background Color
    columnSuffix: ygrlqwwr
    contentColumnType: string
    fieldGroup: null
    handle: panelBackgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - grey
            -
              - value
              - grey
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - transparent
            -
              - value
              - transparent
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  33356ed5-ee39-4b15-8762-22970231ddf4: # Sub Heading (h3)
    columnSuffix: moylrgtu
    contentColumnType: text
    fieldGroup: null
    handle: panelSubheading
    instructions: null
    name: 'Sub Heading (h3)'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentPanel
name: 'Single Text Column'
sortOrder: 1
