field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  a26e8efc-8274-4e15-9434-41135f2514c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 597cef0a-b5bd-4e4c-aec4-2fe935e3b539 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eef18d7f-0a81-45bc-aefc-a440999cb512
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05ace0ab-0445-4076-b3fb-c783e5edd58b # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1d546eb-d645-418d-ae7d-5c9e75ee819b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71f603b5-a762-4ff6-88f0-47bb95d203d8 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f90b8c2-5dae-41c8-83f2-bef0461502ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7f1bfcd-901c-48e8-a97a-447dee253e8f # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51880dc4-9254-4371-bc92-e7bda4507330
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 019ad6dd-97cf-4182-8b61-610bd29ecfbc
        userCondition: null
fields:
  05ace0ab-0445-4076-b3fb-c783e5edd58b: # Sub Heading
    columnSuffix: guvrqqbt
    contentColumnType: text
    fieldGroup: null
    handle: panelSubheading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  71f603b5-a762-4ff6-88f0-47bb95d203d8: # Content
    columnSuffix: fuhkmlxw
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms:
        - 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  597cef0a-b5bd-4e4c-aec4-2fe935e3b539: # Title
    columnSuffix: qlkvhnwq
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c7f1bfcd-901c-48e8-a97a-447dee253e8f: # Background Color
    columnSuffix: xyffkvjb
    contentColumnType: string
    fieldGroup: null
    handle: panelBackgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - grey
            -
              - value
              - grey
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - transparent
            -
              - value
              - transparent
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: contentPanel
name: 'Content Panel'
sortOrder: 1
