field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  b4fb7d8b-7ea0-4e42-a9b3-a0c4c67bb82d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1b4683b2-6086-476d-9ec8-029278f1d3cd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fdc373b-d739-4b30-bba3-3ebd6abb2483
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b147087a-beb7-4822-9a72-e618dfd1852e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 067a5991-0302-4871-bc4b-4f0f785905f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edb9a50f-79f9-48b4-ab66-b8350fd7f21c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 633864f7-9784-4b45-ab05-1cc02f32dbd5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c3a7e78-1d62-4367-8209-f71a5c308a01
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bdb347b-c467-4dfd-a6c3-e1df047f87c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3337bc82-c093-49e0-a82c-521fe046c166
        userCondition: null
fields:
  0c3a7e78-1d62-4367-8209-f71a5c308a01:
    columnSuffix: jzpkbddt
    contentColumnType: string
    fieldGroup: null
    handle: panelBackgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - grey
            -
              - value
              - grey
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - transparent
            -
              - value
              - transparent
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  1b4683b2-6086-476d-9ec8-029278f1d3cd:
    columnSuffix: mwbmxwba
    contentColumnType: text
    fieldGroup: null
    handle: panelSubheading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b147087a-beb7-4822-9a72-e618dfd1852e:
    columnSuffix: dczezwir
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  edb9a50f-79f9-48b4-ab66-b8350fd7f21c:
    columnSuffix: phmxqywv
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms:
        - 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: 1854f0e0-3cd0-4253-a9b0-16473eb338b5 # Deafult
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: contentPanel
name: 'Content Panel'
sortOrder: 1
