field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  7dc2c5d1-1196-44a8-a6e9-d0e2515520da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21fc739b-4753-4a63-b36f-6a542e59b215 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ae947f-eab4-423c-b7f9-c6adeedfa9fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8b3a513-9dc0-464f-92d3-2abee1841ca3 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c8465c9-8be1-429a-a869-7f475045c4d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a67e2336-878a-41a6-90e9-1566f3295e6a # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42cb2d93-5823-4a65-b85e-daea61b00f3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c90456d-1ba4-4a2f-8438-c980af8f79dd
        userCondition: null
fields:
  21fc739b-4753-4a63-b36f-6a542e59b215: # Sub Heading
    columnSuffix: qplniyca
    contentColumnType: text
    fieldGroup: null
    handle: panelSubheading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a67e2336-878a-41a6-90e9-1566f3295e6a: # Content
    columnSuffix: lpbaejvw
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e8b3a513-9dc0-464f-92d3-2abee1841ca3: # Title
    columnSuffix: avfgzsen
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentPanel
name: 'Content Panel'
sortOrder: 3
