field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content
fieldLayouts:
  3f0ebdcd-c7c0-4943-bd61-f7601fb75640:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2b51a4a7-8dc4-4344-a499-4c57992a3c4f # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7558bb69-a02d-4493-8ee9-88d7d7e7348b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 696fb652-ec4c-4eb0-8301-6561412eec27 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6caf92b2-7876-467b-abd2-2b3a4a13d8e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdb8df6b-5d05-42d0-a8b3-a5945e7f8e54 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 645e0c94-cc26-4e7c-b959-ff2e719028be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fabdf510-f296-45c1-8fe8-3e05c9a4918a # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fa19c4b-6f13-41bd-b2a0-8d96951dd33e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 673fd9e1-4575-400c-957a-c033f11e16de
        userCondition: null
fields:
  2b51a4a7-8dc4-4344-a499-4c57992a3c4f: # Link Text
    columnSuffix: afjazdwi
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  696fb652-ec4c-4eb0-8301-6561412eec27: # Link URL
    columnSuffix: xtvjajxt
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkURL
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cdb8df6b-5d05-42d0-a8b3-a5945e7f8e54: # Heading
    columnSuffix: mkarafjb
    contentColumnType: text
    fieldGroup: null
    handle: ctaHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fabdf510-f296-45c1-8fe8-3e05c9a4918a: # Summary
    columnSuffix: eqgpvtzb
    contentColumnType: text
    fieldGroup: null
    handle: ctaSummary
    instructions: null
    name: Summary
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cta
name: 'Call To Action Panel'
sortOrder: 6
