field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  f4690e33-d6f8-45a6-9e3f-007830bc4339:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f61e60f7-7433-4654-a663-ad727ec7beca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98c03950-1099-4ba4-9e2f-a4b620f3dbc5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07dd4b3d-d382-4187-81cd-7843856e053c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8979df4-3e01-436e-9d1d-6113d1dac32e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 873a36d1-d09a-4fc3-88f9-3de2e81bfdee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0f0b8eb-b05c-4437-b972-db5fac0f5e6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d6c73b8-9e64-4551-ad68-5c0cac301214
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b9f4542-1374-4f59-8259-cb53fae19414
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d0bfd59-abb8-43b9-af86-4d03cd7c92e1
        userCondition: null
fields:
  7d6c73b8-9e64-4551-ad68-5c0cac301214:
    columnSuffix: xhpdqzfi
    contentColumnType: text
    fieldGroup: null
    handle: ctaSummary
    instructions: null
    name: Summary
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  07dd4b3d-d382-4187-81cd-7843856e053c:
    columnSuffix: jdsiioae
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkURL
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  873a36d1-d09a-4fc3-88f9-3de2e81bfdee:
    columnSuffix: ifcxswug
    contentColumnType: text
    fieldGroup: null
    handle: ctaHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f61e60f7-7433-4654-a663-ad727ec7beca:
    columnSuffix: difhcgnb
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cta
name: 'Call To Action Panel'
sortOrder: 5
