field: 8d7b11e3-8a9f-4551-8e59-559d5a419a6d # Content Home
fieldLayouts:
  8906676e-ed2c-4eb6-9a39-651918aacfbc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3f1c0c7b-04ca-4d60-90c4-32662f2283ec # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f38b11f-259e-47e1-b256-16807b866992
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01086b62-2763-4aba-b129-39278bab3d75 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 803e4271-42ae-4938-99e2-ebbef025f2dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 494edaaa-a47d-43ec-96be-814e0cbf24d6 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 972c13cf-51d8-4202-aadf-7fdf64792d9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5f1e154-e64e-4d15-99a8-852d01d4958e # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e87f952a-53d5-49d5-bd8d-9ba4e83df438
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e479e8d-22cd-484f-adcd-64e203693522
        userCondition: null
fields:
  3f1c0c7b-04ca-4d60-90c4-32662f2283ec: # Link Text
    columnSuffix: ehhpqyfd
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  494edaaa-a47d-43ec-96be-814e0cbf24d6: # Heading
    columnSuffix: gamksmvc
    contentColumnType: text
    fieldGroup: null
    handle: ctaHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  01086b62-2763-4aba-b129-39278bab3d75: # Link URL
    columnSuffix: icrnlkbc
    contentColumnType: text
    fieldGroup: null
    handle: ctaLinkURL
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f5f1e154-e64e-4d15-99a8-852d01d4958e: # Summary
    columnSuffix: rxxvlunu
    contentColumnType: text
    fieldGroup: null
    handle: ctaSummary
    instructions: null
    name: Summary
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cta
name: 'Call To Action Panel'
sortOrder: 1
