field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  12c6d4a3-d37a-4f4d-8cf9-d017e12404c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d92a774b-27e6-4269-bcf3-39661efc08fa # Subject Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 687ca9f6-3d30-4690-806e-0d710818b123
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ffbae350-a82c-4898-8099-0e129e91b868 # Title Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c209899-e89f-4c7b-850a-31e3f78556d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 951602bb-1e48-456b-886c-67fe46ab4cb3 # Title Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1274951d-b884-4032-8671-5f66a6fe1f1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d94b6905-bfc8-4062-8d2f-8446e7a208c3 # Content Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c0c287c-8ad0-4e0e-9cdc-46f72a2f5466
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6c5c0e5-164a-4340-a52b-501f528ca3b4 # Content Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69ecb64d-3451-4836-abc5-a5deb29b58a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f7fd656-feb2-4d2e-9b98-3f31208557c7 # Subject Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f07ce8a2-65c8-4878-bdd6-7609fe26ecc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b50c90d6-f936-48a0-a517-9ba835ee56a2
        userCondition: null
fields:
  0f7fd656-feb2-4d2e-9b98-3f31208557c7: # Subject Right
    columnSuffix: zttjvihb
    contentColumnType: text
    fieldGroup: null
    handle: subjectRight
    instructions: null
    name: 'Subject Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  951602bb-1e48-456b-886c-67fe46ab4cb3: # Title Left
    columnSuffix: posjlhip
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleLeft
    instructions: null
    name: 'Title Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d6c5c0e5-164a-4340-a52b-501f528ca3b4: # Content Left
    columnSuffix: zslevvsx
    contentColumnType: text
    fieldGroup: null
    handle: panelContentLeft
    instructions: null
    name: 'Content Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d92a774b-27e6-4269-bcf3-39661efc08fa: # Subject Left
    columnSuffix: ecpfvwxo
    contentColumnType: text
    fieldGroup: null
    handle: subjectLeft
    instructions: null
    name: 'Subject Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d94b6905-bfc8-4062-8d2f-8446e7a208c3: # Content Right
    columnSuffix: desarepo
    contentColumnType: text
    fieldGroup: null
    handle: panelContentRight
    instructions: null
    name: 'Content Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ffbae350-a82c-4898-8099-0e129e91b868: # Title Right
    columnSuffix: kwtmvlbv
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleRight
    instructions: null
    name: 'Title Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: doubleTextColumns
name: 'Double Text Columns'
sortOrder: 5
