field: df5feffa-a83a-4b14-9c2f-f1529461780b # Content Home
fieldLayouts:
  39813b59-a239-46e7-abd9-6b2bc4b32916:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8e2d0d22-60a3-43c4-9b2c-06542b3c09db # Subject Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9bc76d4-ad67-4a86-8f74-000bf1b420b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c86aa0c-506c-4214-9a07-72229738379b # Title Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4190e0a-7bb8-4378-97fb-ef9d70ab2626
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b241b239-8363-48e7-b5be-f74aaa0912c1 # Title Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a570a999-9f36-42b1-a3bc-94f96e73e6c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b67e8e0-cc60-4cfe-b394-77b03d4f0fff # Content Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e29d90d-54f7-4dde-9446-d5973074404b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3e4befb-f1d5-4947-99b1-2967dbb1f64d # Content Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df89b522-2a1f-4d6c-98c3-3436aba9b1aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee266199-255b-492e-a88b-4f96c093e273 # Subject Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65cb36d7-4c2f-46aa-90ed-2346b544489d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9605129d-dd2f-4347-82ec-6ea8c668d0ab
        userCondition: null
fields:
  7b67e8e0-cc60-4cfe-b394-77b03d4f0fff: # Content Right
    columnSuffix: ibspcrmb
    contentColumnType: text
    fieldGroup: null
    handle: panelContentRight
    instructions: null
    name: 'Content Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c86aa0c-506c-4214-9a07-72229738379b: # Title Right
    columnSuffix: msxquplh
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleRight
    instructions: null
    name: 'Title Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8e2d0d22-60a3-43c4-9b2c-06542b3c09db: # Subject Left
    columnSuffix: yfozrqgh
    contentColumnType: text
    fieldGroup: null
    handle: subjectLeft
    instructions: null
    name: 'Subject Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b241b239-8363-48e7-b5be-f74aaa0912c1: # Title Left
    columnSuffix: ftyazuog
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleLeft
    instructions: null
    name: 'Title Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3e4befb-f1d5-4947-99b1-2967dbb1f64d: # Content Left
    columnSuffix: kvjjvcwv
    contentColumnType: text
    fieldGroup: null
    handle: panelContentLeft
    instructions: null
    name: 'Content Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ee266199-255b-492e-a88b-4f96c093e273: # Subject Right
    columnSuffix: hubrcxfh
    contentColumnType: text
    fieldGroup: null
    handle: subjectRight
    instructions: null
    name: 'Subject Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: doubleTextColumns
name: 'Text Columns'
sortOrder: 5
