field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  99dcd4eb-8843-4447-b48b-b4b1a70f5f7a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 506fd666-5033-4801-b825-089dbd53a28e # Subject Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b4a9b14-29a3-471d-8871-ed60b587af5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9cd7bf50-46a8-45dd-9dc2-056af2dceb63 # Title Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edbb2522-3f55-4f60-a215-5cd8f9c88271
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ede247a-0b41-45de-81fa-527906aef857 # Title Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a048ecda-a9ca-405a-90aa-4b28db2a3167
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 413d02f2-453a-498b-8cd1-87e49b905a95 # Content Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9eaa087-886c-4fd9-94d3-60424246f9d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ba931e0-10b1-43f0-8f9f-dac8fcf3d800 # Content Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b6406ea-0eaf-4bb2-8355-eafbc9010e5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74461e4b-8289-4afd-ad7c-2768066aad62 # Subject Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 675d9159-b5c0-476b-ac06-fe661159a925
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8761662e-6018-4c7a-b0af-a2794b1cb5b5
        userCondition: null
fields:
  5ede247a-0b41-45de-81fa-527906aef857: # Title Left
    columnSuffix: dcjhlmjy
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleLeft
    instructions: null
    name: 'Title Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9ba931e0-10b1-43f0-8f9f-dac8fcf3d800: # Content Left
    columnSuffix: yorqaeij
    contentColumnType: text
    fieldGroup: null
    handle: panelContentLeft
    instructions: null
    name: 'Content Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9cd7bf50-46a8-45dd-9dc2-056af2dceb63: # Title Right
    columnSuffix: qefdvvll
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleRight
    instructions: null
    name: 'Title Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  413d02f2-453a-498b-8cd1-87e49b905a95: # Content Right
    columnSuffix: knmeijne
    contentColumnType: text
    fieldGroup: null
    handle: panelContentRight
    instructions: null
    name: 'Content Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  506fd666-5033-4801-b825-089dbd53a28e: # Subject Left
    columnSuffix: ddvyccfc
    contentColumnType: text
    fieldGroup: null
    handle: subjectLeft
    instructions: null
    name: 'Subject Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  74461e4b-8289-4afd-ad7c-2768066aad62: # Subject Right
    columnSuffix: ebcqwrhs
    contentColumnType: text
    fieldGroup: null
    handle: subjectRight
    instructions: null
    name: 'Subject Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: doubleTextColumns
name: 'Text Columns'
sortOrder: 5
