field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  537bf3e4-7e15-47c6-9231-7a45ab008445:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 215f0e91-2ea4-4c2f-bc55-e9d8c4045f47
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c4ad43-eeeb-4d66-a997-ab53c6ab595c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9ba174a-caa5-4514-a171-edb324e54882
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 231d69bb-249d-45b4-bed1-7fded51d1fda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf83c836-a6b8-4cdd-8e9c-daec8c107044
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9d352ae-1508-4192-bc79-32b9d7530f80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cfb03e6a-d493-408a-956f-be8ece4f6642
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04711fa9-9bb6-4879-962b-6a311b3d7cbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 047ff52b-632c-479d-8c84-c14330a62df8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6fefa8b-03a6-4079-a233-0e44e8d35909
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: baf0a779-4e63-44a6-89de-05fb119b24ff
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f953b97-50b3-4f7d-bc8f-b2cc8a1bf05a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2adcedc3-e641-4652-9fa8-c1cc197edc2f
        userCondition: null
fields:
  047ff52b-632c-479d-8c84-c14330a62df8:
    columnSuffix: suxiwxxs
    contentColumnType: text
    fieldGroup: null
    handle: panelContentLeft
    instructions: null
    name: 'Content Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  215f0e91-2ea4-4c2f-bc55-e9d8c4045f47:
    columnSuffix: oplwshxa
    contentColumnType: text
    fieldGroup: null
    handle: subjectLeft
    instructions: null
    name: 'Subject Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a9ba174a-caa5-4514-a171-edb324e54882:
    columnSuffix: dvplsmdi
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleRight
    instructions: null
    name: 'Title Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  baf0a779-4e63-44a6-89de-05fb119b24ff:
    columnSuffix: knnjilgs
    contentColumnType: text
    fieldGroup: null
    handle: subjectRight
    instructions: null
    name: 'Subject Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bf83c836-a6b8-4cdd-8e9c-daec8c107044:
    columnSuffix: isjizrhv
    contentColumnType: text
    fieldGroup: null
    handle: panelTitleLeft
    instructions: null
    name: 'Title Left'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cfb03e6a-d493-408a-956f-be8ece4f6642:
    columnSuffix: ebuhfndn
    contentColumnType: text
    fieldGroup: null
    handle: panelContentRight
    instructions: null
    name: 'Content Right'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: doubleTextColumns
name: 'Text Columns'
sortOrder: 4
