field: 1464aa75-afee-4de6-8db0-67994226a779 # Company Links
fieldLayouts:
  6839583d-cf3d-417d-b19b-65f30554c7b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ee855152-e938-4c52-a926-8b120aca878a # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9bd7aa8-b019-4e66-b7d8-eff8c792c1c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69d2ce3a-3133-46ae-a01c-76b2c87e9a90 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eb8d9d3-ad00-4818-b5f4-70edec1e27e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fafd1e25-9141-401d-a96f-e7163608bf8e
        userCondition: null
fields:
  69d2ce3a-3133-46ae-a01c-76b2c87e9a90: # Link URL
    columnSuffix: jsbophfc
    contentColumnType: string(255)
    fieldGroup: null
    handle: footerLinkUrl
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  ee855152-e938-4c52-a926-8b120aca878a: # Link Text
    columnSuffix: xqtqewwe
    contentColumnType: text
    fieldGroup: null
    handle: footerLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: footerLink
name: 'Footer Link'
sortOrder: 1
