field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  9c9aa1f3-fb0d-4622-b613-0200789f387c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 81b916ec-eae4-4463-818e-9e81544212d3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56251633-6d1c-4a89-a521-03ec2e519bdc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ec3aa85-b7b8-4e4c-92b4-9cd5e4cd6c69 # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70950a05-297f-4bde-b8f2-c6b67ef23157
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da59a3ae-6178-4f7c-b665-5ce3ae7e29d7 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9c5c94f-9a72-4ace-9597-fcdc801b33de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55ebc89a-bfff-4044-8701-7d25fedfcffe # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df46ab2f-a12b-40cf-ab01-0c8dfc9ae622
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3a5a6da-435f-4a29-a657-f4cf526e81e5 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbebb763-594c-40ae-9d49-2c7500def01c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88f8b9f3-c3a4-4aba-8c85-9b1acce0cbe4 # Sub Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb8c5507-73f1-42a9-b05a-fffb01d76ed0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06686b29-4528-4e4b-b21d-d2bc339313d3 # Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b130a435-1f7d-4273-89de-fd9c664bca94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f5b0139-ae36-4c36-af29-22838716ea9a # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09ebd704-b1c3-449b-ba1c-c8b88c112b07
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59170d4d-2d04-4c5c-82ec-36f8a5592047
        userCondition: null
fields:
  3f5b0139-ae36-4c36-af29-22838716ea9a: # Link Text
    columnSuffix: flsmyopf
    contentColumnType: text
    fieldGroup: null
    handle: heroLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4ec3aa85-b7b8-4e4c-92b4-9cd5e4cd6c69: # Super Title
    columnSuffix: nzsjykvl
    contentColumnType: text
    fieldGroup: null
    handle: heroSupertitle
    instructions: null
    name: 'Super Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  55ebc89a-bfff-4044-8701-7d25fedfcffe: # Text Position
    columnSuffix: jwvnmpez
    contentColumnType: string
    fieldGroup: null
    handle: heroTextPosition
    instructions: null
    name: 'Text Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  81b916ec-eae4-4463-818e-9e81544212d3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroBackgroundImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  88f8b9f3-c3a4-4aba-8c85-9b1acce0cbe4: # Sub Title
    columnSuffix: xwxazflp
    contentColumnType: text
    fieldGroup: null
    handle: heroSubtitle
    instructions: null
    name: 'Sub Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  06686b29-4528-4e4b-b21d-d2bc339313d3: # Link Url
    columnSuffix: tqcmhufb
    contentColumnType: string(255)
    fieldGroup: null
    handle: heroLinkUrl
    instructions: null
    name: 'Link Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a3a5a6da-435f-4a29-a657-f4cf526e81e5: # Title
    columnSuffix: rxzorrme
    contentColumnType: text
    fieldGroup: null
    handle: heroTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  da59a3ae-6178-4f7c-b665-5ce3ae7e29d7: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroVideo
    instructions: null
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: hero
name: Hero
sortOrder: 6
