field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  d4c557dc-85b7-4dea-8dda-80a878ccca51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f7aae0f-02c0-4ea3-b3a5-a9073b29991e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05e12943-0cf1-4567-8463-497ade9f766d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 690cb815-b85f-467e-a047-43e23b08ee2b # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d75a4fd3-6163-4f56-ac1c-ffcee2c12d0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2070cdb0-2bf5-4ec9-bcc2-7086f75c8f29 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fcb8285-122d-4e55-a34b-76555f2b12ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15e254f0-a128-4ec1-88b9-b754fcb121ee # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ee1103e-57ba-450d-b354-8312856173b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bdd3bf2-3db4-435f-aea7-89660ac769e3 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5700f38c-20a5-4ffe-9635-0db8277e3192
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86bc8e7a-cd28-4c53-b542-4c88a24dc76c # Sub Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0265f500-d7af-48dc-99bd-48c73a38e87c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05986233-da3a-4937-85f9-b2b7784bc596 # Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c48d217-254f-453c-90d7-7ecdf925a9dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5628d29-8e5c-49cd-97e7-ccc8a9d42ae4 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8bfb9f6-915d-452e-9ab0-f8123183ca4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 273bea04-54d4-4583-b2bb-331dac0a7cbe
        userCondition: null
fields:
  5bdd3bf2-3db4-435f-aea7-89660ac769e3: # Title
    columnSuffix: fcxlihzt
    contentColumnType: text
    fieldGroup: null
    handle: heroTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7f7aae0f-02c0-4ea3-b3a5-a9073b29991e: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroBackgroundImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  15e254f0-a128-4ec1-88b9-b754fcb121ee: # Super Title
    columnSuffix: sjgegmim
    contentColumnType: text
    fieldGroup: null
    handle: heroSupertitle
    instructions: null
    name: 'Super Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  86bc8e7a-cd28-4c53-b542-4c88a24dc76c: # Sub Title
    columnSuffix: sngyymey
    contentColumnType: text
    fieldGroup: null
    handle: heroSubtitle
    instructions: null
    name: 'Sub Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  690cb815-b85f-467e-a047-43e23b08ee2b: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroVideo
    instructions: null
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2070cdb0-2bf5-4ec9-bcc2-7086f75c8f29: # Text Position
    columnSuffix: entuaemo
    contentColumnType: string
    fieldGroup: null
    handle: heroTextPosition
    instructions: null
    name: 'Text Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  05986233-da3a-4937-85f9-b2b7784bc596: # Link Url
    columnSuffix: ykyrsium
    contentColumnType: string(255)
    fieldGroup: null
    handle: heroLinkUrl
    instructions: null
    name: 'Link Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b5628d29-8e5c-49cd-97e7-ccc8a9d42ae4: # Link Text
    columnSuffix: jtixingb
    contentColumnType: text
    fieldGroup: null
    handle: heroLinkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hero
name: Hero
sortOrder: 6
