field: df5feffa-a83a-4b14-9c2f-f1529461780b # Content Home
fieldLayouts:
  19ef404b-6d97-42f0-909d-0c12fbbfd8de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 782e1b6a-790a-43e7-ac90-96687597e319 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0625c260-c90e-4750-ab9f-53d00955dac1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c775643-0aac-4173-9282-6c3dafa2e85f # Image Behavior
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8f58a3c-7438-4884-97d5-04c103fc4d7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c441b249-bf42-433d-b3a1-2def1393feb9 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42c84582-a35d-4fca-ba88-ce978593347c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8da7fff3-7a7e-4325-afe0-9b06bb1ed6cf
        userCondition: null
fields:
  1c775643-0aac-4173-9282-6c3dafa2e85f: # Image Behavior
    columnSuffix: rnvvveed
    contentColumnType: string
    fieldGroup: null
    handle: imageBehavior
    instructions: null
    name: 'Image Behavior'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - full
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Contained
            -
              - value
              - contain
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  782e1b6a-790a-43e7-ac90-96687597e319: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c441b249-bf42-433d-b3a1-2def1393feb9: # Caption
    columnSuffix: fnpdcohz
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imagePanel
name: 'Image Panel'
sortOrder: 4
