field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  ab462ca9-6783-4978-986f-494e3e8cc0e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 814bdcfe-3124-4f34-b8f9-871e98fbc82f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63d88c2c-39cf-47ba-8dfd-194ace030843
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dc03b28-34bb-4082-a680-4fe41216a6d6 # Image Behavior
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a098b18c-6523-443b-aa11-a42850fdc85f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1d461f0-3a18-4e35-bed5-a494f95b6bcd # Box Shadow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 653aca52-b340-40b0-b975-b826a1d3b63e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae857f6a-20ef-4267-ba7e-2569f68bfb1a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7929541-8129-4c0c-9bb3-4d0ffdd1af92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab49e488-9485-4b3b-87f2-dd0ea10a4725 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8aacc0a-b604-48ea-b10a-f42e4bf21daa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65d09ba0-c32c-4de9-9519-c1fac8d17b2d
        userCondition: null
fields:
  3dc03b28-34bb-4082-a680-4fe41216a6d6: # Image Behavior
    columnSuffix: hgtabexx
    contentColumnType: string
    fieldGroup: null
    handle: imageBehavior
    instructions: null
    name: 'Image Behavior'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full Width Bleed'
            -
              - value
              - full
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '100% Container Width'
            -
              - value
              - contained
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  814bdcfe-3124-4f34-b8f9-871e98fbc82f: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ab49e488-9485-4b3b-87f2-dd0ea10a4725: # Caption
    columnSuffix: qlgpotbw
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ae857f6a-20ef-4267-ba7e-2569f68bfb1a: # Heading
    columnSuffix: nyzhzsge
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e1d461f0-3a18-4e35-bed5-a494f95b6bcd: # Box Shadow
    columnSuffix: fbcoekax
    contentColumnType: string
    fieldGroup: null
    handle: imageBoxShadow
    instructions: null
    name: 'Box Shadow'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No'
            -
              - value
              - 'no'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: imagePanel
name: 'Image Panel'
sortOrder: 3
