field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  29bb1cbd-78ef-4284-ace8-43bc79180dba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b4b55ce3-b751-45e8-bbfd-00f7a2db916d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7bd5a42-5139-443a-90f4-bcd951278a0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4446b2a-3b34-4d3f-aed5-e60b6e72d197
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f856cdfb-1182-44a6-b21a-6b618923594e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 924dc6c0-9486-4338-a91b-99c8682adb04
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e81e93-227f-4fcf-8d9a-7d2914d155eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eabf767a-914f-4579-abd9-843f59023231
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dafb1fff-243a-442c-8e5e-2d7409120c11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4430797-fe88-4718-a38d-32f0f11be070
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c77afa66-8879-4a25-9f2f-ce26c4043f4a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6169608b-8f9c-46f0-a896-4e172eaa040e
        userCondition: null
fields:
  924dc6c0-9486-4338-a91b-99c8682adb04:
    columnSuffix: iudbnuzf
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a4430797-fe88-4718-a38d-32f0f11be070:
    columnSuffix: xgwcxmxr
    contentColumnType: string
    fieldGroup: null
    handle: imageBoxShadow
    instructions: null
    name: 'Box Shadow'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No'
            -
              - value
              - 'no'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  b4b55ce3-b751-45e8-bbfd-00f7a2db916d:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e4446b2a-3b34-4d3f-aed5-e60b6e72d197:
    columnSuffix: ociywokd
    contentColumnType: string
    fieldGroup: null
    handle: imageBehavior
    instructions: null
    name: 'Image Behavior'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - full
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Contained
            -
              - value
              - contain
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  eabf767a-914f-4579-abd9-843f59023231:
    columnSuffix: pdyqorjn
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imagePanel
name: 'Image Panel'
sortOrder: 3
