field: df5feffa-a83a-4b14-9c2f-f1529461780b # Content Home
fieldLayouts:
  3efc9f45-7bae-4d8a-ae06-b8c6052e0e1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6e68a8b3-7a3c-40b8-b30b-4275fba41e4e # Subject
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46daf98e-c53d-4213-8b77-cff2a6c57f25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98758e9a-baa8-4869-b1d4-3606bc8e2e37 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9af7043-ee3d-475c-8fbd-7241c1a4006b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5663a898-2246-4b0e-bd1f-a2d7e7c83d78 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80b60d72-3a73-4373-9969-fb01e950799f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec12c69e-c5dc-414d-a452-a04051f2d911 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b3a120f-6392-4c4d-89a3-12d96646e408
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8007fc25-3d33-4ee5-ade0-cadfb61b1591 # Image Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bef6ab38-4e90-41f5-8273-06597fce0ae1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01a501a6-9b5a-4653-a80d-b53da41c1984
        userCondition: null
fields:
  6e68a8b3-7a3c-40b8-b30b-4275fba41e4e: # Subject
    columnSuffix: vlzucxfu
    contentColumnType: text
    fieldGroup: null
    handle: subject
    instructions: null
    name: Subject
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5663a898-2246-4b0e-bd1f-a2d7e7c83d78: # Title
    columnSuffix: kvpvpefq
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8007fc25-3d33-4ee5-ade0-cadfb61b1591: # Image Position
    columnSuffix: guqwwzlo
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  98758e9a-baa8-4869-b1d4-3606bc8e2e37: # Content
    columnSuffix: czfrpxhy
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      defaultTransform: null
      initJs: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  ec12c69e-c5dc-414d-a452-a04051f2d911: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageTextPanel
name: 'Image and Text Panel'
sortOrder: 1
