field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  e9445aed-2501-4a92-b5d7-2a54ef3824c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3a66029f-ef5b-468f-933e-ed82347b358b # Subject
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb8ccdc2-1889-44d1-bedd-5229020fba80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5807a47-39e7-480a-ab04-0e0c4d998d82 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8551a47-1d53-40fc-ab58-4c4d736f1f2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e8877f3-dede-4da7-b2ff-b99da1322eb8 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6efc707a-c949-49a3-bdbf-ea6751681d1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5de6fb93-f0d9-4e60-8aee-655fff872dbc # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ffc8649-23c0-4e03-8fcc-bcf2c069508e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87380890-913a-4519-9afb-69424757bfc7 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3f7bc8e-8363-46d9-a476-ed597a398545
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3be11231-26fa-497b-8791-d2e78eb7493b # Image Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d75759f0-6f9f-4413-8a44-d8c2b517330d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c663cc6-3b87-4ae9-8c64-27167163a9a6 # Image Box Shadow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a3be6f0-9c00-42d1-8a91-d6f63aa12577
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30ce25e1-5493-463f-8fe4-999eb6849126 # Picture Column Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bd5e573-7485-4585-bca6-154f404d769e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 783d9775-a9da-416f-ba1b-4cd043918a18
        userCondition: null
fields:
  3a66029f-ef5b-468f-933e-ed82347b358b: # Subject
    columnSuffix: argbmcdd
    contentColumnType: text
    fieldGroup: null
    handle: subject
    instructions: null
    name: Subject
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3be11231-26fa-497b-8791-d2e78eb7493b: # Image Position
    columnSuffix: idgcjvks
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  5de6fb93-f0d9-4e60-8aee-655fff872dbc: # Content
    columnSuffix: moqzzvci
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5e8877f3-dede-4da7-b2ff-b99da1322eb8: # Subtitle
    columnSuffix: tuahsjic
    contentColumnType: text
    fieldGroup: null
    handle: panelSubtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6c663cc6-3b87-4ae9-8c64-27167163a9a6: # Image Box Shadow
    columnSuffix: haisovgp
    contentColumnType: string
    fieldGroup: null
    handle: imageBoxShadow
    instructions: null
    name: 'Image Box Shadow'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No'
            -
              - value
              - 'no'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  30ce25e1-5493-463f-8fe4-999eb6849126: # Picture Column Width
    columnSuffix: zpebfklc
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Picture Column Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 25%
            -
              - value
              - '25'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - '50'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  87380890-913a-4519-9afb-69424757bfc7: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5807a47-39e7-480a-ab04-0e0c4d998d82: # Title
    columnSuffix: crabwwyc
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageTextPanel
name: 'Image and Text Panel'
sortOrder: 3
