field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  2b6070ce-1a64-42ee-b035-07a16a2d9447:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e5718ec8-8743-49be-a621-a4f3bff26155
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 038f7ca1-2667-4b56-9a26-c9168aa8787b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2543a140-b507-4821-8f98-f8081d2d86af
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eded889-7666-4230-b912-9521e354681a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1e0c5fb-3990-45b6-ba81-90c7d963dd65
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e7a1ebe-3ab8-4710-a392-30c4e8e8da16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c8a45b1-774b-49ba-8368-7e5f765de447
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a15c809-752c-45ef-99fb-676225289599
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cef48517-39f9-4709-9f50-c7383c36e91c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ac2d03d-6c43-4bfe-a613-1bfdd5a701b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58eccfac-1a04-4fa8-a35b-f29bb0537ef4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c53b3636-9f36-4651-afe9-0026dff28df3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56ded7a3-d2bc-49c4-aadb-68d8716801e5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc88aaf0-1d12-469b-82c4-a985eef5e2cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73a5d409-74ac-41f6-8e80-19c64954f05a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccf06623-5387-49df-bc2d-e8787eafc066
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8db4e3ee-3522-48ae-8e84-2e593dbe1849
        userCondition: null
fields:
  3c8a45b1-774b-49ba-8368-7e5f765de447:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  56ded7a3-d2bc-49c4-aadb-68d8716801e5:
    columnSuffix: jyaryhgk
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Picture Column Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 25%
            -
              - value
              - '25'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - '50'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  58eccfac-1a04-4fa8-a35b-f29bb0537ef4:
    columnSuffix: gbgbgczw
    contentColumnType: string
    fieldGroup: null
    handle: imageBoxShadow
    instructions: null
    name: 'Image Box Shadow'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No'
            -
              - value
              - 'no'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  73a5d409-74ac-41f6-8e80-19c64954f05a:
    columnSuffix: mxryrcyn
    contentColumnType: text
    fieldGroup: null
    handle: panelSubtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2543a140-b507-4821-8f98-f8081d2d86af:
    columnSuffix: whadgebk
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b1e0c5fb-3990-45b6-ba81-90c7d963dd65:
    columnSuffix: xetugdzx
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cef48517-39f9-4709-9f50-c7383c36e91c:
    columnSuffix: kxabhipu
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  e5718ec8-8743-49be-a621-a4f3bff26155:
    columnSuffix: cfdftsho
    contentColumnType: text
    fieldGroup: null
    handle: subject
    instructions: null
    name: Subject
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageTextPanel
name: 'Image and Text Panel'
sortOrder: 2
