field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  503a84ef-837f-422c-b822-b9cfb7331e51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d75ab3d3-0adc-4c01-95f4-1312f3438ad8 # Subject
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1ab0ca8-8931-432e-a50a-0e9bccfc6497
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e9112d5-e8e2-4bf3-b8bf-6aabf22dba02 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7304988-1007-40f9-b4a3-cae38f27eb89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 126d62dc-06ff-4092-b459-9d70201fb6a6 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee61ac27-81c1-4c0e-b4d1-31684b47cd23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5da24cee-ec7b-4943-95db-6445a180b092 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1258de73-9458-4f97-983b-14f1d274fed4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 240d961f-7e8c-4b8c-b31d-a929b8a857de # Image Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54719e91-8dfe-4569-a653-bb8d3f02c203
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d5ea587-cd6a-4d7d-b8f5-e278cccf3bf4 # Image Box Shadow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d8441da-435a-4b48-b90a-c099177ec7c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dc810b9-5e90-47f0-be2d-18ff5d560d5e # Picture Column Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fc8bb85-aef7-40e3-98d9-6c5b5f027d48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e717b878-e2de-4ed7-94a1-7eef2c75c2f4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d247dc1-51d3-4e1e-8119-fb718ac3edaa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b517d43e-66c3-4a1a-aeff-1d9f7a14e079
        userCondition: null
fields:
  3d5ea587-cd6a-4d7d-b8f5-e278cccf3bf4: # Image Box Shadow
    columnSuffix: ilvgmqpl
    contentColumnType: string
    fieldGroup: null
    handle: imageBoxShadow
    instructions: null
    name: 'Image Box Shadow'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No'
            -
              - value
              - 'no'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  3dc810b9-5e90-47f0-be2d-18ff5d560d5e: # Picture Column Width
    columnSuffix: qofwiizo
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: null
    name: 'Picture Column Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 25%
            -
              - value
              - '25'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - '50'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  5da24cee-ec7b-4943-95db-6445a180b092: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2ff0c12-9108-4b60-b65e-9effcc913281' # Projects
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  5e9112d5-e8e2-4bf3-b8bf-6aabf22dba02: # Content
    columnSuffix: odfgjfgn
    contentColumnType: text
    fieldGroup: null
    handle: panelContent
    instructions: null
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  126d62dc-06ff-4092-b459-9d70201fb6a6: # Title
    columnSuffix: cgthqdvf
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  240d961f-7e8c-4b8c-b31d-a929b8a857de: # Image Position
    columnSuffix: catblxou
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  d75ab3d3-0adc-4c01-95f4-1312f3438ad8: # Subject
    columnSuffix: cobvtthh
    contentColumnType: text
    fieldGroup: null
    handle: subject
    instructions: null
    name: Subject
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e717b878-e2de-4ed7-94a1-7eef2c75c2f4: # Subtitle
    columnSuffix: yidunvqg
    contentColumnType: text
    fieldGroup: null
    handle: panelSubtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageTextPanel
name: 'Image and Text Panel'
sortOrder: 1
