field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  43862ce5-b5a5-4b30-8f74-2324b1a1e78c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 70a258c5-7119-407e-83ae-18a8b70590e2 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 027ae707-a906-414a-8070-cb9692c7407a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66f3e21d-e765-45d3-8f6f-dcddecf9e2af # Projects Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45e73168-943e-45bb-a0a4-06e81390c543
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bbf94b0-e2bb-4ef3-9ac1-638238d54e95
        userCondition: null
fields:
  66f3e21d-e765-45d3-8f6f-dcddecf9e2af: # Projects Limit
    columnSuffix: pbienozh
    contentColumnType: integer(10)
    fieldGroup: null
    handle: projectsLimit
    instructions: null
    name: 'Projects Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 9
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  70a258c5-7119-407e-83ae-18a8b70590e2: # Heading
    columnSuffix: itkkuhue
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: projectsRollup
name: 'Projects Rollup'
sortOrder: 11
