field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  0c6b6410-b396-46dc-9982-24ca7758823a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 702b4ab5-aec1-4d04-8d6e-1972ef29664d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8d9faa-a883-4f4f-8e23-d4b8cb2015fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43ce31d5-37ed-4b92-9010-996d2d6a5694 # Projects Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a239cd2b-1eb4-4c35-a4fc-4ec1fef05395
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 74b6fd9f-249b-42d7-a2f8-9dd267db16e4
        userCondition: null
fields:
  43ce31d5-37ed-4b92-9010-996d2d6a5694: # Projects Limit
    columnSuffix: wjjbtxwl
    contentColumnType: integer(10)
    fieldGroup: null
    handle: projectsLimit
    instructions: null
    name: 'Projects Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 9
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  702b4ab5-aec1-4d04-8d6e-1972ef29664d: # Heading
    columnSuffix: abehkipi
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: projectsRollup
name: 'Projects Rollup'
sortOrder: 11
