field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  01a42938-5e43-42e4-8a82-bc5f00052ff0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b548e8a9-957e-45e1-b50e-7d0ebbc7af43
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d478f4-9fe6-40d5-b738-37b87c851b66
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6de22fcc-cac6-4613-9873-d72e9096dd1d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8016dadc-b79b-400d-aa56-0ebc005edac3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ffb2d2b-072e-43ee-8518-06c73fb3ea6c
        userCondition: null
fields:
  6de22fcc-cac6-4613-9873-d72e9096dd1d:
    columnSuffix: hdsoujvk
    contentColumnType: integer(10)
    fieldGroup: null
    handle: projectsLimit
    instructions: null
    name: 'Projects Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 9
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  b548e8a9-957e-45e1-b50e-7d0ebbc7af43:
    columnSuffix: jxtpjrqp
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: projectsRollup
name: 'Projects Rollup'
sortOrder: 9
