field: df5feffa-a83a-4b14-9c2f-f1529461780b # Content Home
fieldLayouts:
  3a21f943-cf98-4a59-91f2-eb842ac5d0ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1a47a2a1-be15-45b5-b8b4-73078d135b00 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57907309-1f02-4405-8b3e-a6ab9b88ac56
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 711fa1de-ef75-4399-bbfe-badcb165f8ec # Projects Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21fc7afe-4320-4086-82fa-11d0e6465cb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0acf11d-91ef-47ce-82ef-a210e7a26685
        userCondition: null
fields:
  1a47a2a1-be15-45b5-b8b4-73078d135b00: # Heading
    columnSuffix: krgmmltx
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  711fa1de-ef75-4399-bbfe-badcb165f8ec: # Projects Limit
    columnSuffix: zpauhssr
    contentColumnType: integer(10)
    fieldGroup: null
    handle: projectsLimit
    instructions: null
    name: 'Projects Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 9
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: projectsRollup
name: 'Projects Rollup'
sortOrder: 2
