field: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
fieldLayouts:
  cba99a3f-c468-4c33-a7b3-3063292c8e5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1664b5ae-26d9-489d-806f-92bf711be8c7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 598bf2a5-6701-41fd-885a-e5c5179c48a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfb5fe6a-ff67-4c22-97b3-03cb427ed972 # Project Slug
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faddd4e3-1078-4387-8e5d-5e3fc2324275
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92151c4c-e2c2-40a8-82dc-eaea2b06af45
        userCondition: null
fields:
  1664b5ae-26d9-489d-806f-92bf711be8c7:
    columnSuffix: fsbgbhgr
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dfb5fe6a-ff67-4c22-97b3-03cb427ed972: # Project Slug
    columnSuffix: hcqxgopo
    contentColumnType: text
    fieldGroup: null
    handle: projectsSlug
    instructions: null
    name: 'Project Slug'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Slug
                -
                  - handle
                  - slug
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: 3
      minRows: 2
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: relatedProjects
name: 'Related Projects'
sortOrder: 7
