field: df5feffa-a83a-4b14-9c2f-f1529461780b # Content Home
fieldLayouts:
  5e7079f0-ca9c-4b84-823d-f70e82743785:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 392a5840-4224-4dc1-8d57-0296ac0dc4d9 # Project Slug
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8416b9cc-1740-4b75-a89f-eeb946ea1b38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0e35bb-24b0-4d5d-9ad8-df4932968e62 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ac4cecd-1b49-42aa-ac50-bfff36c9667a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65edd6fa-4009-4962-98e9-baf63adef2d2
        userCondition: null
fields:
  8c0e35bb-24b0-4d5d-9ad8-df4932968e62: # Heading
    columnSuffix: sjedipln
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  392a5840-4224-4dc1-8d57-0296ac0dc4d9: # Project Slug
    columnSuffix: xvxmzbro
    contentColumnType: text
    fieldGroup: null
    handle: projectsSlug
    instructions: null
    name: 'Project Slug'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Slug
                -
                  - handle
                  - slug
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: 3
      minRows: 2
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: relatedProjects
name: 'Related Projects'
sortOrder: 7
