field: c789f365-f8f1-4dce-8ea9-f22d79885c3a # Content 2
fieldLayouts:
  824ffbb8-e124-403d-b23e-f20c97fd5f3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: deb37763-ceb6-4097-922d-cc149a193913 # Project Slug
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff807c83-1f17-4f4d-9304-689b1c115dab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4566f2f9-cc72-4524-95e2-5a83af98f5c8 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b99b992-8b1b-4eef-a10d-cdba599f107d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24a3bfdc-655e-41b3-8427-149c8076d3c9
        userCondition: null
fields:
  4566f2f9-cc72-4524-95e2-5a83af98f5c8: # Heading
    columnSuffix: hbkykgzy
    contentColumnType: text
    fieldGroup: null
    handle: projectsPanelHeading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  deb37763-ceb6-4097-922d-cc149a193913: # Project Slug
    columnSuffix: knprgxrc
    contentColumnType: text
    fieldGroup: null
    handle: projectsSlug
    instructions: null
    name: 'Project Slug'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Slug
                -
                  - handle
                  - slug
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: 3
      minRows: 2
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: relatedProjects
name: 'Related Projects'
sortOrder: 7
