field: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
fieldLayouts:
  33623c4e-5ce5-44d6-92ec-2e7dd70e268c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 333b5bb7-a3ff-462a-a446-d6abf71f99c4 # Services Panel Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6aeaca7b-32d4-469e-829d-00fb44cc343d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e7343e7-5a3c-4976-ab37-e07c94b7c944 # Services Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f564f2d-4d6a-4a5b-b7cd-2c2ddcbff99a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff7bac76-5caa-4e51-8ad2-c326feba4e89
        userCondition: null
fields:
  1e7343e7-5a3c-4976-ab37-e07c94b7c944: # Services Panel Heading
    columnSuffix: byyagxtp
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelHeading
    instructions: null
    name: 'Services Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  333b5bb7-a3ff-462a-a446-d6abf71f99c4: # Services Panel Subheading
    columnSuffix: thohmxoc
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelSubheading
    instructions: null
    name: 'Services Panel Subheading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: servicesRollup
name: 'Services Rollup'
sortOrder: 10
