field: 07f7e5cb-0101-478c-9bc6-2e533fdd83be
fieldLayouts:
  0f6eb772-8d54-4193-8201-092bf57bd63f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 43642b25-873b-4bff-9c7f-1701db58684a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14a5f7a9-a60d-4e07-8bb5-1070e1267919
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6c5af49-fc1f-4848-8230-8531dc2d2d88
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c18ac23f-24cd-47dd-87a4-13d1da2392b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66375d9e-cd0f-4897-8fb1-f7cf2801a490
        userCondition: null
fields:
  43642b25-873b-4bff-9c7f-1701db58684a:
    columnSuffix: ukuzywju
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelSubheading
    instructions: null
    name: 'Services Panel Subheading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a6c5af49-fc1f-4848-8230-8531dc2d2d88:
    columnSuffix: dlqgtunc
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelHeading
    instructions: null
    name: 'Services Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: servicesRollup
name: 'Services Rollup'
sortOrder: 8
