field: 8d7b11e3-8a9f-4551-8e59-559d5a419a6d # Content Home
fieldLayouts:
  6cf56e31-5ef3-4493-beb5-4e803b67313a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8a7da287-263d-4b22-b1d2-c341fad34a88 # Services Panel Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9479eb0b-e94b-4495-bbb9-71fba7df7fd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed55b31d-a94a-4380-8548-8f72dc97732b # Services Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15782eec-6dae-4493-9cf1-c7ce315bc055
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc3191c2-9d3f-4831-90d6-da0406596e1d
        userCondition: null
fields:
  8a7da287-263d-4b22-b1d2-c341fad34a88: # Services Panel Subheading
    columnSuffix: xttxuecm
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelSubheading
    instructions: null
    name: 'Services Panel Subheading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed55b31d-a94a-4380-8548-8f72dc97732b: # Services Panel Heading
    columnSuffix: nlmyaolx
    contentColumnType: text
    fieldGroup: null
    handle: servicesPanelHeading
    instructions: null
    name: 'Services Panel Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: servicesRollup
name: 'Services Rollup'
sortOrder: 3
