fieldLayouts:
  656dac67-8205-4de5-a674-70ba6ba15db0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: 'Content (above values)'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c35f3579-b176-419c-bc69-f7f0896e6f49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36cde833-6bde-43bd-b40d-d47db1bc4577 # Content 2
            instructions: null
            label: 'Content (below team members)'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 873805a4-02c4-468d-a31d-b533fa9ed42b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f8a0374-8ac6-470d-9b69-944219dc3e99
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9f272002-9f4a-4175-bd11-86b7a26fe9ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39ce3f74-ea40-48bd-a6e1-3251031cee8b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07d5fb26-3812-40a1-bee6-9d696f45dc28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 112efcad-1a5a-40bd-87f8-dc0ea2e5f742 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43f2d88c-929e-44f3-858f-83cbc8e2d927
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c29a686-fff4-421f-a776-99099065609a # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d10e0e-0c47-4aa1-9107-5de81e6d209a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55aeb36a-1a23-40a5-b308-cd2b88181da7 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36065c4f-d63d-403b-a961-06476af905c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 818276ab-339c-4835-80cf-0d925ad564cc # Hero Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18a3cae7-cc47-4379-b78c-23a7037199b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18995cfd-16c6-457d-8ead-6dadaf3f1d09 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ae38abc-1f0d-4c64-8f62-3f2a298f6003
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b391a624-f2b4-474c-b0ef-a640f03c071b # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e88beb-69c0-4a3f-9642-830857441646
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7166386d-a511-42df-a908-1e859dfba3e2 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a953e5a-df55-4a53-a288-48a9981a5966
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: f5bb8497-43db-469c-9f5f-afd5e00aab72
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 399ae674-015d-4a9a-8d92-ca90c1795e9a # Values Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba61fc3d-08d8-4306-9c54-3622218cf4a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 19ea1aa2-c9e0-4d79-b0fb-44ee39962600 # Values
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0d5ee96-b502-4e27-acbf-30c944a02226
            userCondition: null
            warning: null
            width: 100
        name: Values
        uid: dccb7ae3-6096-41f8-9f32-3642bad6a05f
        userCondition: null
handle: company
hasTitleField: false
name: Company
section: 52756a4b-7e10-4fec-a57a-8599921de625 # Company
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
