fieldLayouts:
  8c714ded-2f6a-4437-81f8-49c181962f54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0bdd8071-8cbf-4872-b179-28e82da4cac4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dba3b1b9-5ee4-4471-917f-320573bbfdfc
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: dfb093fd-8fb2-4785-b71c-6cac631336ad # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
