fieldLayouts:
  1ba046da-1ddf-487e-b2c9-38b568a40461:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a3398cfd-e05e-4e1f-8f5f-9a7641d66335
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cad340b4-a5a3-4e74-b80c-6d94bd7dd4f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e5536fa-68f3-403a-8111-e8d431262396
        userCondition: null
handle: contactSuccess
hasTitleField: false
name: 'Contact Success'
section: 312a1ef9-dccd-4c4c-a3d0-46925368bfaf # Contact Success
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
