fieldLayouts:
  8092ed6c-e165-496b-be1a-08be9bbe1cc9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df3156de-6146-4d1d-9618-bd2ac26a1832
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8f6afd5-4eb0-4f9f-9791-88b26e03e9e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8127d1c8-49fe-4562-baf1-58ff5a80ffda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12c4284f-ef55-4f05-b11c-ef3e46a06a5b # Client
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e199c9ae-7347-4688-a0ae-4528ae1cd4fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2819c3c-3e2f-451d-bb6a-1054eec8014f # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a239dbf5-c471-4faa-8ed5-5ad566ab788b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5b8be6a-fa7e-4457-ba84-2dbf40eac704 # Project Tags
            instructions: null
            label: 'Featured Filter Tags'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d820ff1d-2aaf-4b09-b68b-c61212193c76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4286b563-2204-41e7-b3ef-832fb11cd7e1 # Related Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f468249-7955-4c73-9ca2-944a9549d5fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9126f58d-d92d-42a3-b976-80161de3a478 # Rollup Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73eab484-55c9-43f8-a105-cdfb81508da5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b2271de-7d81-4a96-8a7d-a22ee9982c33 # Description
            instructions: null
            label: 'Featured Rollup Description'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a6f1cc1-ab9f-4b10-bacc-5b53893f2b6b
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 15915f92-5890-4e88-9c51-1226017806a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 39ce3f74-ea40-48bd-a6e1-3251031cee8b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e39f589-500c-4820-b8ef-9fa801ed1e07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c29a686-fff4-421f-a776-99099065609a # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce874e74-757c-48c1-be04-b69813e62d98
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 112efcad-1a5a-40bd-87f8-dc0ea2e5f742 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f28f519-0658-416f-be7b-646c34deb6cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 818276ab-339c-4835-80cf-0d925ad564cc # Hero Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9dc1492-ea99-4c09-beba-b94d2ffd69eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55aeb36a-1a23-40a5-b308-cd2b88181da7 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 361e73fb-1f4f-4cd9-9a78-97f6e63d9747
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7166386d-a511-42df-a908-1e859dfba3e2 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97ca1785-c2ef-48cf-bac7-41848ba8c600
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18995cfd-16c6-457d-8ead-6dadaf3f1d09 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2310b3d7-0d4c-4f53-8e8c-21a52d3c1a2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b391a624-f2b4-474c-b0ef-a640f03c071b # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fade2e41-19e1-44e0-9f33-6fc9f60621c2
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: ee73bd39-cac1-45af-a7c0-40fcbf8cc6d9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4cb46986-1520-4dea-b94b-64b8b7d942d1 # Related Projects Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0f5a41f-b912-4da1-bc43-bb955d7f9d4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a4b90a2-3d20-4ada-b63b-13d70c710333 # Related Projects Slug
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c51ce630-2855-41da-923b-0d9ba975abfa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2236215-c720-4eb3-925a-05cb3e4d42ca # Content Card Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c0197c3-7e19-4d54-9af9-4858e11f7583
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6590dc4b-f1f2-4771-aedc-ac9da2e0dfe4 # Card Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46976b54-b934-49f5-a037-24b906c6d630
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af54f917-7fe8-486c-b610-5d5d135e73d9 # Card Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52225bac-e158-4576-b4ac-6f9f6e069ff7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 706a7c05-d62a-469a-9d9f-0c307db9c4f7 # Card Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0de7275-5f50-4098-80ba-6b54175905d1
            userCondition: null
            warning: null
            width: 100
        name: 'Related Projects'
        uid: 9cf307ee-a6c9-4468-94f7-e0b0708a68e3
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 4554b864-9bc7-4e0d-9a92-41307f4cef13 # Projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
