fieldLayouts:
  3c8cda13-5dc5-451b-aeec-6d448d7fbaba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1e2f7825-d80f-4fb1-bc48-a1df1d0c381a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 211f8030-0715-4db5-85d0-7c70298eb02d # Content Sections Panel Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06696e5b-9380-41a9-973e-f568913978a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f19d591-ce53-4c98-92b2-e7b515f83b64
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68ebfb10-859d-4c60-901c-20fa1970eeb7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 475c7edd-ba22-46da-8dca-8dc985338cb2 # Services Rollup Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 858a5c63-31c2-4c65-b580-e3838b95d117
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 277862de-1b83-406a-a0bf-a30726615b44 # Services Rollup Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b234cf7-7fe7-40a7-8561-ca71e6870a72
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: c2fa21d2-b957-43c6-ae9d-c5a94a1f4926
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4cb46986-1520-4dea-b94b-64b8b7d942d1 # Related Projects Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39641bd4-bd17-475b-b518-303e31e09798
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a4b90a2-3d20-4ada-b63b-13d70c710333 # Related Projects Slug
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f96579ec-9f09-43ee-94e5-5631cdc62351
            userCondition: null
            warning: null
            width: 100
        name: 'Related Projects'
        uid: 381d6f73-5e6b-4ae4-91fd-865c87d48313
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 39ce3f74-ea40-48bd-a6e1-3251031cee8b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ddfb967-4c7d-45a8-8bd2-1cab0a78fa75
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 40bbb3ca-a68d-4c49-9d26-e5c0e405c7c5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: bf6214ea-1eff-41d8-ad8a-28c854c848c3 # Services
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
