fieldLayouts:
  909a8946-127e-41f9-9ecd-d5633caff40a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 783283f1-d7af-4353-8a41-d9fc0cf76191
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 211f8030-0715-4db5-85d0-7c70298eb02d # Content Sections Panel Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e0b946e-d27e-459f-95ef-47826358e29f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bf72b8d-7c20-4aa6-9b4c-2521a3fef22c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c1dc13a-0bfa-49e4-95b5-f87bc89aa610
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a40dfa81-d145-4d0d-98c8-eac1172ccd51 # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a3178bd-fec9-46bc-b1c3-c7f267706d80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70f522d3-f030-4bdc-9292-b039000c85f8 # Rollup Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f1e570b-9190-4e88-a641-52050bc1dea4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f64dd4b-f512-46bb-9f6a-4a4b9afb2810 # Rollup Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9456095d-7d21-4799-9bd5-0c05a575b737
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: afd0ea6f-4716-40cf-9cab-998b877589f6 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1f06253-8677-483e-9de9-0cc7d0d45256
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cac5b961-0cd3-4762-8120-ff63f84fbfe0 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c56a8776-a83e-4290-ab07-31420d124ecb
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: ee0d6f04-d1eb-462c-adaf-e8c63a09efc2
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7b9f31e0-a9e2-4b32-9da7-f3e032fefc67 # Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
