fieldLayouts:
  5eb9cd09-b6f4-4f3b-bc1c-90389dc48c54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3a1b114-c34b-464b-8a63-18b382f44ad1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 211f8030-0715-4db5-85d0-7c70298eb02d # Content Sections Panel Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09896d32-34e2-4120-a2c6-85c0856cc2c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d08ca6d-5bed-4b0f-bf30-531b81ce438a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: adeeb1d8-b55d-4170-b843-a14991efcb7c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c29a686-fff4-421f-a776-99099065609a # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12a8023e-1d5d-48c7-a2e0-7ffb8aa54633
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39ce3f74-ea40-48bd-a6e1-3251031cee8b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce2fc00b-55c6-4b99-ae44-c491ac67b1ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 112efcad-1a5a-40bd-87f8-dc0ea2e5f742 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b6597d3-60ce-43c9-80aa-37cbb2c195c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7166386d-a511-42df-a908-1e859dfba3e2 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b410c401-f467-4e84-8f03-7b6783bdbc0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 818276ab-339c-4835-80cf-0d925ad564cc # Hero Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b991235-bfa3-45a7-8e59-20e8fb95af9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55aeb36a-1a23-40a5-b308-cd2b88181da7 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb57e77a-bfc1-4ab6-a1d3-7236df64dd2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18995cfd-16c6-457d-8ead-6dadaf3f1d09 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 120f4b05-6b72-4421-9faa-bc28f9b8c00a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b391a624-f2b4-474c-b0ef-a640f03c071b # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bde94ae-a491-4458-bfb4-7a8dad07cc97
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: cbac14f3-1784-49df-9c27-0e11437401b0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 09e51889-5c1b-4472-bdda-e495b8d2712f # Card Heading Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cec13fe7-cbe4-4342-b81a-3f519f29cb8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d9fd9f9-49cb-4c71-aec0-c2907bd1886e # Sub Heading Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81117066-2d03-49ad-b7ec-6b13190b492f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e4e1f8b-b4a5-4c61-a795-c399cf229104 # Card Summary Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af6c3dcc-f81f-4a4b-92cb-49308238b6e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcd08c3e-474c-46ac-b0a3-96b749d96ff2 # Link Text Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6678c1b1-ee5a-43a9-80c8-ee29f7a06803
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b18925c-a6af-476b-918e-196b1323c4c9 # Link URL Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c97db5c-a474-4cec-966c-9b9f5e559be0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52401f4b-7fb8-42e1-98d5-420030c54889 # Card Heading Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62643be3-dbf2-49b8-985a-178d259a2675
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b8518e1-54b6-4973-97bc-366ecf10191c # Sub Heading Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8329d93a-f91b-4c93-9cf0-2af23aa97554
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ca063e7-abb4-44e2-b815-749d6a5498c0 # Card Summary Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 040229cb-4f60-4e20-b189-6d8753447ff4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5596da7-7785-4432-8d8c-5ce2a7fcce94 # Link Text Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54dde3c9-3f39-406e-bd98-7a45a578a2d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08388c84-a061-4a11-8031-eb3a17b8c932 # Link URL Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f07d8ce8-7282-423f-b480-22f4ffdaf4d9
            userCondition: null
            warning: null
            width: 100
        name: 'Service Cards'
        uid: 9e17abcd-dec1-41c8-9e5b-ed03ec08a381
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 51dda47a-1f3e-4d90-9c5e-231c491a11e5 # Featured Projects Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ee9311b-023f-4980-848c-77306541353a
            userCondition: null
            warning: null
            width: 100
        name: 'Featured Projects'
        uid: 9023b4ca-9139-40be-99c3-d53ff0a67513
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: b834c143-a4d7-4d69-92b8-7f3e442af425 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
