fieldLayouts:
  5eb9cd09-b6f4-4f3b-bc1c-90389dc48c54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3a1b114-c34b-464b-8a63-18b382f44ad1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d08ca6d-5bed-4b0f-bf30-531b81ce438a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c1cc454-aca1-4dc5-8ab8-220b7257e993 # Panel Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4981fc81-16fe-477c-a1be-329aab10915b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: adeeb1d8-b55d-4170-b843-a14991efcb7c
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: b834c143-a4d7-4d69-92b8-7f3e442af425 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
