fieldLayouts:
  37218111-7b8b-4452-a45e-19f0070106d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 88a7a273-6ac0-493c-80c4-03022c8c870a # Show Disciplines Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1371944-db41-4a2e-a609-30e1310b2810
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: decd8b6d-bb52-417b-9572-0a9e873b774c # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3625a943-c324-4133-b130-85ac582d63a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3f3df94-b233-4ca3-9685-05e13af84f1d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1ddbf71f-d9a8-42ee-ba2b-b5b232186fec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39ce3f74-ea40-48bd-a6e1-3251031cee8b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae85fc56-0e4d-4a60-ae98-45518322ad1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86832c8f-0e26-4321-892d-3f2b670e5d40 # Hero Title (line 2)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26eecace-71a4-440b-98d6-bcc95836a897
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 112efcad-1a5a-40bd-87f8-dc0ea2e5f742 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fc0b62c-c4e2-4a6b-bc5d-1904351a1240
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c29a686-fff4-421f-a776-99099065609a # Super Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d5039c9-ee51-4325-bbcf-63edf35b465d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55aeb36a-1a23-40a5-b308-cd2b88181da7 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c658ca86-6584-4bec-b1c1-76bed6e106a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b391a624-f2b4-474c-b0ef-a640f03c071b # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bedf2ce-92e3-4743-9f67-96ff5e09a0ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 818276ab-339c-4835-80cf-0d925ad564cc # Hero Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6098b110-f5f9-4f2a-9489-9792d2dc565d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18995cfd-16c6-457d-8ead-6dadaf3f1d09 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25b597dd-ac5e-4a9a-a8cf-6b39f68d1da9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7166386d-a511-42df-a908-1e859dfba3e2 # Text Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6478991-f160-451a-9da5-982cd9e6c6c9
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 64929393-23a8-4305-9d90-f0b646b8bc88
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4cb46986-1520-4dea-b94b-64b8b7d942d1 # Related Projects Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c5e15fc-5b84-42b5-8317-6bab10e81bf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a4b90a2-3d20-4ada-b63b-13d70c710333 # Related Projects Slug
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 058be1ff-7f71-4e9e-9a1b-f4524893c455
            userCondition: null
            warning: null
            width: 100
        name: 'Related Projects'
        uid: c801c755-cb85-413d-a9bf-9779c2878d57
        userCondition: null
handle: startUp
hasTitleField: true
name: Start-up
section: b3d6f87a-a321-46e7-91f8-b0039347d167 # Start-up
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
