fieldLayouts:
  aad5163e-8202-4d84-a68a-5b62c614dcc7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 77da6491-1ac2-475e-9a90-81e700e40ba0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a5d2eaf-58ac-4ce7-8fe8-f74f8e09c192
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
