columnSuffix: ygklciqv
contentColumnType: string
fieldGroup: 312438a4-60cf-4fd0-85e1-2146d8d36657 # Common
handle: contentPanels
instructions: null
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentpanels}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
