columnSuffix: zxxkybwq
contentColumnType: smallint(3)
fieldGroup: 1b4cc869-d062-4e3e-889e-419528ae7deb # Hero
handle: heroObjectPosition
instructions: null
name: 'Vertical Background Position'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 100
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
