columnSuffix: cugluoxy
contentColumnType: text
fieldGroup: cd8f97bb-1019-4201-947a-62825eab84e5 # Projects
handle: projectsLink
instructions: null
name: 'Projects Link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
