columnSuffix: tydlstao
contentColumnType: string(255)
fieldGroup: cd8f97bb-1019-4201-947a-62825eab84e5 # Projects
handle: projectsBackgroudImageUrl
instructions: null
name: 'Background Image Url'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
