columnSuffix: null
contentColumnType: string
fieldGroup: cd8f97bb-1019-4201-947a-62825eab84e5 # Projects
handle: projectsTags
instructions: null
name: 'Project Tags'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'taggroup:47dc5f60-5afa-437b-9370-a9b213c9ab47' # Projects
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
