columnSuffix: bfgobsmx
contentColumnType: text
fieldGroup: cd8f97bb-1019-4201-947a-62825eab84e5 # Projects
handle: relatedProjectsContentCardSummary
instructions: null
name: 'Card Summary'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: 'Get in touch with us to...'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
