columnSuffix: bogatwlz
contentColumnType: text
fieldGroup: cd8f97bb-1019-4201-947a-62825eab84e5 # Projects
handle: relatedProjectsContentCardTitle
instructions: null
name: 'Content Card Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Start your project'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
