columnSuffix: awvpkbmo
contentColumnType: text
fieldGroup: 20318baf-14d6-49f8-964e-a646e56d5446 # Footer
handle: tagline
instructions: null
name: Tagline
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
