defaultPlacement: end
enableVersioning: true
handle: featuredProjects
name: 'Featured Projects'
propagationMethod: all
siteSettings:
  ada35ad0-4d42-4ca8-bed9-59ff6816f33f: # Tangent Services
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 030d6a24-5a1f-49e4-bbef-9ae63ea45061
type: structure
