defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  ada35ad0-4d42-4ca8-bed9-59ff6816f33f: # Tangent Services
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
